### ISSUE TITLE
Safari Layout a bit off

### ISSUE THREAD

**Issue by bkniffler** [chatscope/chat-ui-kit-react#1]
Here is a Screenshot:
<img width="553" alt="Bildschirmfoto 2020-10-26 um 10 37 40" src="https://user-images.githubusercontent.com/4349324/97156805-85e73000-1777-11eb-8adc-b64ea0fb1d61.png">

**Comment by supersnager** [comment]
@bkniffler Thank you, i wil check it.

**Comment by supersnager** [comment]
Fixed in styles release [1.0.6](https://github.com/chatscope/chat-ui-kit-styles/releases/tag/v1.0.6) https://github.com/chatscope/chat-ui-kit-styles/releases/tag/v1.0.6
