### ISSUE TITLE
Backspace not working from inside MessageInput component

### ISSUE THREAD

**Issue by ebeastlake** [chatscope/chat-ui-kit-react#107]
Hitting "delete" on Mac is not triggering the change handler in the MessageInput component. How can I fix that?

**Comment by ebeastlake** [comment]
Using `onKeyDown` to detect backspace is a workaround, but I assume the behavior is still unintended.

**Comment by supersnager** [comment]
@ebeastlake I tested it using Browserstack on Mac Ventura in Chrome 113 and Safari 16.3 and it works.
Please provide a repro and detailed info about the browser and Mac version.
