### ISSUE TITLE
Message.Header / Footer do not appear if using the 'direction' property

### ISSUE THREAD

**Issue by Johnne25** [chatscope/chat-ui-kit-react#11]
This shows the header:
```
<Message model={{
  message: "Hello my friend",
  sentTime: "just now",
  sender: "Joe"
}}>
<Message.Header sender="Emily" sentTime="just now" />
</Message>
```

This one does not:
```
<Message model={{
  message: "Hello my friend",
  sentTime: "just now",
  sender: "Joe",
  direction: "incoming",
}}>
<Message.Header sender="Emily" sentTime="just now" />
</Message>
```

**Comment by supersnager** [comment]
@Johnne25 Thank you for your report. It's a bug in [@chatscope/chat-ui-kit-styles](https://github.com/chatscope/chat-ui-kit-styles) repository.
Please watch a dedicated issue there: chatscope/chat-ui-kit-styles#2

**Comment by supersnager** [comment]
I have added an explanation https://github.com/chatscope/chat-ui-kit-styles/issues/2#issuecomment-778210038
