### ISSUE TITLE
Using defaultProps is deprecated

### ISSUE THREAD

**Issue by KDederichs** [chatscope/chat-ui-kit-react#119]
Hi,
it'd be great if you could switch all the uses of `defaultProps` with just passing the parameters in the method signature.
Using `defaultProps` is deprecated and spams the console with warnings as well.

**Comment by AlexShavkuta** [comment]
Hi,
Is there any updates on this?

**Comment by Zakariaels** [comment]
hi there, is there any updates on this issue ?

**Comment by supersnager** [comment]
@KDederichs @AlexShavkuta  @Zakariaels I'm almost done. I need to finish rewriting of the last few stories and make some cosmetic changes. I think it'll take me a few of days.

**Comment by Zakariaels** [comment]
@supersnager, Thanks for your efforts!
Don't hesitate if you need some help :)

**Comment by supersnager** [comment]
Good news! Storybook v7.6.17 has just landed on the site.
Now I will do a review of the #120 and merge!

**Comment by supersnager** [comment]
Finally released, as major version v2.0.3.

@KDederichs Thank you for your effort!
@nathanstitt  Your issue with class components mentioned here: https://github.com/chatscope/chat-ui-kit-react/pull/120#issuecomment-1922433248 has also been resolved

**Comment by remoun** [comment]
Hi, I'm using v2.0.3 and still getting an exception saying "Warning: FontAwesomeIcon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."

I'm using the code from the Default sample (first one) from https://chatscope.io/storybook/react/?path=/docs/components-maincontainer--docs with NextJS 14.1.0 and React 18.2.0

**Comment by supersnager** [comment]
@remoun That is a warning from fontawesome. Please see this comment https://github.com/chatscope/chat-ui-kit-react/pull/120#issuecomment-1922433248
