### ISSUE TITLE
Keep disabled MessageInput sendButton when text is none even if props is given.

### ISSUE THREAD

**Issue by naninanya** [chatscope/chat-ui-kit-react#126]
Hi.

I want to manage MessageInput sendButton wthere is enable or not,
but I found if we set sendDisabled props of MessageInput, sendButton even used props value when input text is none. 

Would you change the above priority?

**Comment by supersnager** [comment]
@naninanya Thank you for the question. 
This can't be changed. The property sendDisabled is to force disabling send button independent of the input value.
The Proposed change would make this flag unneccesary.
You can track message input value and set sendDisabled to undefined or false when the value of the input is empty.
