### ISSUE TITLE
Formatting AvatarGroup in ConversationHeader

### ISSUE THREAD

**Issue by Anjum48** [chatscope/chat-ui-kit-react#128]
I'm using AvatarGroup in ConverstationHeader, but it's not formatting correctly - avatars are stacking vertically instead of horizontally:
![image](https://github.com/chatscope/chat-ui-kit-react/assets/13783303/f68c0a70-a293-47ac-9bdc-b34cfdf889d0)

I'm seeing the same with ConverstationList also.

Any idea on how to make it appear as it does in the storybook? Thanks!

**Comment by supersnager** [comment]
@Anjum48 Please paste the header code

**Comment by Anjum48** [comment]
Here's the header code:
```javascript
<ConversationHeader>
  <ConversationHeader.Back />
  <AvatarGroup size="md" max={2}>
    {currentConv.names.map((c, i) => (
      <Avatar
        src={currentConv.avatar[i]}
        name={currentConv.names[i]}
        key={"Avatar" + i}
      />
    ))}
  </AvatarGroup>
  {/* <Avatar
    src={currentConv.avatar[0]}
    name={currentConv.names[0]}
  /> */}
  <ConversationHeader.Content userName={currentConv.title} />
  <ConversationHeader.Actions>
    <AccountMenu />
  </ConversationHeader.Actions>
</ConversationHeader>
```
The styles are applied from `import styles from "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css";`

**Comment by Anjum48** [comment]
I think I fixed this with CSS. Turns out that `.cs-conversation-header__avatar` and `.cs-conversation-list__avatar` need their own specific CSS for the desired behaviour
