### ISSUE TITLE
Can we have load more and scroll feature in Conversation List .

### ISSUE THREAD

**Issue by GhazanfarKhan** [chatscope/chat-ui-kit-react#13]
Hi again, Thanks for the great work.

My conversation list are large. I need to add load more functionality similar to MessageList one. Is it possible?

**Comment by supersnager** [comment]
@GhazanfarKhan
Yes it's possible :)
Please describe more how do you want to do it.
Do you want to do infinite scroll like here (in the opposite direction, of course):

https://chatscope.io/storybook/react/?path=/docs/components-messagelist--loading-more-state#loading-more-state

or rather add a "Load more" button at the bottom of the conversation list?

**Comment by GhazanfarKhan** [comment]
Not like Message List in which we scroll on reverse direction. This will be normally infinite scroll like downwards. Yes you can add load more button or which ever you feel like is easy and can be done fast :)

**Comment by GhazanfarKhan** [comment]
Hi @supersnager. When are you planning this feature ?

**Comment by supersnager** [comment]
Hi @GhazanfarKhan I'll take care of it tomorrow

**Comment by supersnager** [comment]
@GhazanfarKhan I have added two new features:

1. onYReachEnd property
2. loadingMore state

It works the same as in MessageList.
You can make infinite scroll using these features.

[@chatscope/chat-ui-kit-react v1.3.0](https://github.com/chatscope/chat-ui-kit-react/releases/tag/v1.3.0)
Required styles:
[@chatscope/chat-ui-kit-styles v1.1.0](https://github.com/chatscope/chat-ui-kit-styles/releases/tag/v1.1.0)

Example in documentation: [ConversationList infinity scroll example](https://chatscope.io/storybook/react/?path=/docs/components-conversationlist--loading-more-state)
