### ISSUE TITLE
Typing effect animation

### ISSUE THREAD

**Issue by Razi-abedi** [chatscope/chat-ui-kit-react#130]
I want to implement the typing effect animation for the incoming messages, but it is not applied. Any suggestions?

**Comment by supersnager** [comment]
@Razi-abedi Please clarify. Share some code, what exaclty is going on?

**Comment by Razi-abedi** [comment]
I want to implement the typing effect as the one in chatGPT in my app. I wonder if chatscope library has this functionality handled in the frontend. I tried using the type animation library. but it does not work with chatscope. Thansk

**Comment by supersnager** [comment]
There is a ```<TypingIndicator />``` component.

You can pass it to the ```<MessageList />```
```tsx
<MessageList typingIndicator={<TypingIndicator content="Eliot is typing" />}>
```

You can also use your own indicator.

Component docs: https://chatscope.io/storybook/react/?path=/docs/components-typingindicator--default-story
Usage: https://chatscope.io/storybook/react/?path=/docs/components-messagelist--long-list-with-scrollbar
