### ISSUE TITLE
Unexpected overflow on ChatContainer

### ISSUE THREAD

**Issue by AdrKacz** [chatscope/chat-ui-kit-react#141]
While using the `ChatContainer`, this one extends the window to its maximum to display messages, which is very annoying. How can I reproduce the same behavior that in the demo https://chatscope.io/demo/chat-friends: the ChatContainer keeps a **fixed** height.

When the ChatContainer is empty, it is set to the height I want, the problem happens when it starts having too much message and needs to grow.

I am not using the `MainContainer`, I just need the `ChatContainer` (it looks like the demo is using the `MainContainer`)

Thank you,

*PS: You are doing an amazing work, this package is awesome!*

**Comment by notzane** [comment]
You can use `MainContainer` with no `Sidebar` elements to get just a `ChatContainer`.
```
<MainContainer>
  <ChatContainer>
    // content
  </ChatContainer>
</MainContainer>
```

**Comment by supersnager** [comment]
@AdrKacz simply add height to the ```ChatContainer``` component.

```tsx
<ChatContainer style={{height:"300px"}}>
  <MessageList>
  </MessageList>
</ChatContainer>
```
