### ISSUE TITLE
transitionning between the chatcontainer and the sidebar in mobile display

### ISSUE THREAD

**Issue by Med-Fedi-Adel** [chatscope/chat-ui-kit-react#142]
Hello , it's not really an issue but I'm working with this library and I'm having hard time to write a bit of code to transition from the chatContainer to the Sidebar by clicking on the Back arrow located in the start of Conversation Header. I just need a bit of help in the css and state management to make the sidebar appear with full width on the screen and the ChatContainer is hidden.

Example : 

When I click on this back arrow for example : 
![Capture d'écran 2024-01-21 230148](https://github.com/chatscope/chat-ui-kit-react/assets/124141462/1bda1b30-cbe0-4c42-8586-a7095d8d4d98)

My goal is something similar to this : 
![Capture d'écran 2024-01-21 230018](https://github.com/chatscope/chat-ui-kit-react/assets/124141462/888385e1-10ee-4a6a-9cd0-ca7fd612f3e9)

**Comment by notzane** [comment]
Try something like this, call `setShowSidebar(true)` in your back button and `false` when you tap a thread.
```tsx
const [showSidebar, setShowSidebar] = useState(true); // start with sidebar showing

return (
  <MainContainer>
    {showSidebar ? ( // if true render the sidebar content
      <Sidebar>
        { sidebar content }
      </Sidebar>
    ) : ( // else render the chat content
      <ChatContainer>
        { chat content }
      </ChatContainer>
    )
 </MainContainer>
)

```

**Comment by vishalbhan** [comment]
Here's the implementation based from the chatscope storybook: 
[https://chatscope.io/storybook/react/?path=/docs/components-maincontainer--default-story#toggle-conversation-list-using-the-back-button](https://chatscope.io/storybook/react/?path=/docs/components-maincontainer--default-story#toggle-conversation-list-using-the-back-button)

**Comment by supersnager** [comment]
@vishalbhan gave an answer so I'm closing the issue. @Med-Fedi-Adel if you still have problem with this, please reopen.
