### ISSUE TITLE
Unexpected width and height change inside components in Message.HtmlContent.

### ISSUE THREAD

**Issue by nathaliaspinula** [chatscope/chat-ui-kit-react#144]
Hi. I'm trying to render a chart with chart.js inside the Message component, but when the mouse hovers over the message, the library updates the height and width size to zero and the chart disappear.

Here is my code.

`<Message model={{
            direction: "incoming",
            position: "single",
            type: "custom"
          }}>
            <Message.HtmlContent html="<div style={{width:200, height:200}}><canvas id='graph-image-content' width='200' height='200'/></div>" />
          </Message>
`

How can I use a canva component inside message.htmlcontent without having it changed?

**Comment by supersnager** [comment]
@nathaliaspinula I think the problem lies somewhere in your code or in the settings of the chart.js library. I checked your example and nothing happens when you hover the mouse over the message.
If you still can't find a solution please provide a full repro.
