### ISSUE TITLE
[HELP] How to use the streaming message feature? 

### ISSUE THREAD

**Issue by vishnu-dev** [chatscope/chat-ui-kit-react#145]
List of features on [chatscope.io/features](https://chatscope.io/features/) states

> not only for chat, but also useful for any feeds, article comments, and social media posts comments, **real time streaming comments**, sms/text conversations etc..

But, I couldn't find an example on how to use this feature. Can someone point me in the right direction? For example: Which component to use?

**Comment by supersnager** [comment]
@vishnu-dev @chatscope/chat-ui-kit-react is a UI library independent of communication and data delivery libraries.
You can use for example the  ```MessageList``` and ```Message``` components to display messages in the order they are received, but how you receive the message stream  is up to you. For example you can use [websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) or [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) for that.

**Comment by OlofHarrysson** [comment]
I'm also looking for a way to stream messages piece by piece, like chatGPT

**Comment by vishnu-dev** [comment]
> @vishnu-dev @chatscope/chat-ui-kit-react is a UI library independent of communication and data delivery libraries. You can use for example the `MessageList` and `Message` components to display messages in the order they are received, but how you receive the message stream is up to you. For example you can use [websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) or [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) for that.

Thank you for the reply. I was able to achieve the desired results.

**Comment by timbrownca** [comment]
Would you be willing to share details of how you implemented the streaming? I’m interested in doing it as well so would love to know what works. TIA!
