### ISSUE TITLE
Is there a way to actually set a proper max-length for MessageInput?

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [chatscope/chat-ui-kit-react#154]
Trying to get the maximum length of the message content that the user has typed, however depending on the length of the message it will give me either a string with just the message or a string of html code that contains a ton of span tags. This is making it impossible to determine the actual length of the content in the message that the user has typed.

This also means that by sending the input of the message to a websocket is trying to send a message with a length of 15549 when really its only supposed to be 512.

Essentially I'm looking for a way to send the actual message itself, not the html that it keeps providing.

My chatbox component below:
```js
import React, { useState, useEffect, useRef } from 'react'
import { useSelector } from 'react-redux'

import styles from "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css"
import { MainContainer, ChatContainer, MessageList, Message, MessageInput } from "@chatscope/chat-ui-kit-react"

export default function Chatbox() {
	const userId = useSelector( state => state.user.userId )
	const [ inputValue, setInputValue ] = useState( '' )
	const [ messages, setMessages ] = useState( [] )
	const ws = useRef( null )

	useEffect( () => {
    	ws.current = new WebSocket( 'ws://localhost:4000/chat' )

    	ws.current.onopen = () => {
			console.log( 'WebSocket connected' )
    	}

		ws.current.onmessage = ( event ) => {
			const messageObject = JSON.parse( event.data )
			setMessages( ( prevMessages ) => [ ...prevMessages, messageObject ] )
		}

		ws.current.onclose = () => {
			console.log( 'WebSocket disconnected' )
		}

		return () => {
			ws.current.close()
		}
	}, [] )

	const handleSend = () => {
		let msg = inputValue.trim()
		console.log(msg, msg.length)

		if ( msg && msg.length <= 12054 ) {
			ws.current.send( msg )
			setInputValue( '' )
		}
	}

	return <div style={ { position: "relative", height: "500px" } } >
		<MainContainer>
			<ChatContainer>
				<MessageList>
					{ messages.map( ( msg, index ) => (
            			<Message key={ index } model={ {
							message: `[${msg.userRole.toUpperCase()}]${msg.userName}(${msg.timestamp}): ${msg.text}`,
							direction: msg.userId === userId ? "outgoing" : "incoming"
						} }/>
			        ) ) }
				</MessageList>
				<MessageInput attachButton={false} placeholder="Type message here" value={inputValue} onChange={ setInputValue } onSend={ handleSend } />
			</ChatContainer>
		</MainContainer>
	</div>
}
```

**Comment by supersnager** [comment]
@The-Lord-of-Owls onChange handler receives four parameters. 
Depending on your needs You can use one of them to get the length.

The signature of the onChange handler is:
```typescript
(innerHtml: String, textContent: String, innerText: String, nodes: NodeList) => void
```
Ref:
https://chatscope.io/storybook/react/?path=/docs/components-messageinput--docs#props
https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText
https://developer.mozilla.org/en-US/docs/Web/API/NodeList
