### ISSUE TITLE
Issues formatting Conversations and Avatars

### ISSUE THREAD

**Issue by Johnne25** [chatscope/chat-ui-kit-react#17]
I am using Avatar, Name and Unread Count in my Conversation component.
Here is my Converstation code:

```
    renderAvatar = () => {
        // return <Avatar name='John'/>;
        
        const avtr = require('../../../img/highway.png');
        return avtr;
    }
    
    renderConversation = (index, selected) => {
        const img = this.renderAvatar()

        return (
            <div as Conversation  className='conversation' key={`con${this.props.conversation.conversations[index].id}`}>
                <Conversation 
                        onClick={() => this.conversationClick(this.props.conversation.conversations[index].id)}
                        name={this.props.conversation.conversations[index].name} info="Available" unreadCnt={this.props.conversation.conversations[index].unreadCount}>
                    <Avatar src={img} />
                </Conversation>
            </div>
        );
    }
```
I find the displaying of the actual Avatar image to be very hit and miss.  
I would like to use a custom avatar instead of hardcoded png files.
So far, most of my images I have tried do not work.

Ideally, I would like to use the 'react-avatar' package to display customer avatars on the fly.
But I can't get it to work. You can see in the `renderAvatar() `method above that I wanted to return the Avatar instead of a png file.

```
import Avatar from 'react-avatar';
import { Avatar as ChatAvatar } from '@chatscope/chat-ui-kit-react'; // needed to change your name to avoid conflict

<ChatAvatar src={<Avatar name='John'/>} />

```

**Comment by supersnager** [comment]
@Johnne25 It the same as in the previous question in #12.

First of all **src** property of  **&lt;Avatar /&gt;** component accepts only image path, so you can't provide Avatar from react-avatar package by this property.

So in short, please try this:

in file MyAvatar.js define your custom avatar 
```jsx
import Avatar from "react-avatar"
export const MyAvatar () => <Avatar />
```
in main file
```jsx
import {Avatar} from "@chatscope/chat-ui-kit-react";
import MyAvatar from "./MyAvatar";
<MyAvatar as={Avatar} src={<Avatar name='John'/>} />
```

or this:
```jsx
import ReactAvatar from "react-avatar";

<ReactAvatar as="Avatar" size="40px" name="Lilly" />
// You can also add chatscope avatar class to react-avatar
<ReactAvatar as="Avatar" size="40px" className="cs-avatar" name="Lilly" />
```
Of course, it can require some CSS tweaking.

Please note: "as" property can be passed also as a string with component name, so you can combine it in many ways

**Comment by supersnager** [comment]
Related to: #8

**Comment by Johnne25** [comment]
Thanks.
