### ISSUE TITLE
Word wrap is required on messages.

### ISSUE THREAD

**Issue by Johnne25** [chatscope/chat-ui-kit-react#18]
When displaying received messages work wrap should be used.

Right now when display messages parts of a word will appear on two lines.

ie:
"I think this thing needs to have wo
rd wrap"

**Comment by supersnager** [comment]
Fixed in  [@chatscope/chat-ui-kit-styles#1.1.1](https://github.com/chatscope/chat-ui-kit-styles/releases/tag/v1.1.1)
You must upgrade styles package for it.
