### ISSUE TITLE
MessageList Infinite Scroll Bottom with loading spinner

### ISSUE THREAD

**Issue by pateljoel** [chatscope/chat-ui-kit-react#19]
Is there a way to have a message list's infinite scroll work in the similar way to a conversation lists infinite scroll?

Currently the MessageList's infinite scroll is at the top, I would like it at the bottom with a loading spinner like a twitter feed.

Is this possible?

**Comment by supersnager** [comment]
@pateljoel Thanks for the question. 

Displaying the loader on the bottom is not yet supported out of the box. 

I can add new property **loadingMorePosition** = "top"|"bottom", and **onYReachEnd** to &lt;MessageList /&gt;.
Will it be ok for you?

**Comment by pateljoel** [comment]
@pateljoel Yep, this is fine with me.

**Comment by pateljoel** [comment]
@supersnager Also, the other day I tried to join the Discord but the link was invalid.

**Comment by supersnager** [comment]
Done in [v1.4.0](https://github.com/chatscope/chat-ui-kit-react/releases/tag/v1.4.0)
This feature requires [@chatscope/chat-ui-kit-styles@1.2.0](https://github.com/chatscope/chat-ui-kit-styles/releases/tag/v1.2.0)

New **&lt;MessageList /&gt;** properties:

- loadingMorePosition
- autoScrollToBottom
- onYReachEnd

Example:  https://chatscope.io/storybook/react/?path=/story/components-messagelist--loading-more-at-the-bottom

@pateljoel Please let me know if it works for you.
Thanks also for the info about the problem with the link to the Discord :)

**Comment by pateljoel** [comment]
@supersnager I've tried this out and it looks and works good, but every time I load the message list, the onYReachEnd keeps getting called because the scrollbar knob is by default positioned at the bottom.

Is it possible to position the scrollbar knob at the top of the list instead of the bottom?

**Comment by supersnager** [comment]
@pateljoel Have you tried to set **autoScrollToBottom** property of the &lt;MessageList /&gt; to false?

**Comment by pateljoel** [comment]
@supersnager I've used the prop already, and it still scrolls to the bottom.

**Comment by supersnager** [comment]
@pateljoel Do you mean it scrolls down automatically after the first render? Or do you scroll down after adding more messages?

**Comment by pateljoel** [comment]
@supersnager sorry, it scrolls down automatically after the first render.

**Comment by supersnager** [comment]
@pateljoel Ok thanks for the clarification. I will add a separate property for it.

**Comment by supersnager** [comment]
Done in: [v1.5.0](https://github.com/chatscope/chat-ui-kit-react/releases/tag/v1.5.0)

Doc: https://chatscope.io/storybook/react/?path=/story/components-messagelist--disable-auto-scroll-to-bottom-on-first-render
