### ISSUE TITLE
Copying message copy span html instead of text

### ISSUE THREAD

**Issue by GhazanfarKhan** [chatscope/chat-ui-kit-react#22]
Hi, when you copy a message from message component it will copy html not the actual text. Attaching screenshot.

![image](https://user-images.githubusercontent.com/16287368/113062656-845de000-91cd-11eb-9bbc-6b6c30241a4a.png)

**Comment by GhazanfarKhan** [comment]
![image](https://user-images.githubusercontent.com/16287368/113129419-4d6ee500-9234-11eb-9ce6-53b3625896be.png)
It is accepting any html.

**Comment by GhazanfarKhan** [comment]
Is there any way I can disable html pasting

**Comment by supersnager** [comment]
@GhazanfarKhan Thank you for your question.

If you need to sanitize data pasted to **&lt;MessageInput /&gt;**, you can use **onPaste** event handler.

Here is simple example:
```javascript
  const [ value, setValue ] = useState(""); 

  return <MessageInput  onChange={(val) => setValue(val)} value={value} onPaste={(evt) => {
                evt.preventDefault();
                setValue(evt.clipboardData.getData("text"));
         }} />
```

**Comment by GhazanfarKhan** [comment]
@supersnager thanks.

**Comment by GhazanfarKhan** [comment]
Hi @supersnager 

Send button is disabled when do the above steps you describe.

**Comment by GhazanfarKhan** [comment]
Hi @supersnager, send button id disabled while do pasting but when I type something it was undisabled.

**Comment by supersnager** [comment]
@GhazanfarKhan Internal state of a send button is tracked by onChange internal handler. Paste event, not invokes this handler.
I will think, how to deal with it when the paste event occurs.

However, as a workaround, you can use the **sendDisabled** property of the **&lt;MessageInput /&gt;** component to handle the state of this button yourself:

```javascript
  const [ value, setValue ] = useState(""); 
  const [sendDisabled, setSendDisabled] = useState(true);
            useEffect(() => {
                setSendDisabled(value.length===0);
            },[value]);

  return <MessageInput  sendDisabled={sendDisabled} onChange={(val) => setValue(val)} value={value} onPaste={(evt) => {
                evt.preventDefault();
                setValue(evt.clipboardData.getData("text"));
         }} />
```

**Comment by GhazanfarKhan** [comment]
Thanks for this workaround.
