### ISSUE TITLE
react17 support

### ISSUE THREAD

**Issue by kolt-suzuki** [chatscope/chat-ui-kit-react#25]
It's great if this library works with react17.
Is there any reason to have peerDependency with React16.14?

**Comment by supersnager** [comment]
@kolt-suzuki Thanks for your question.
I'm using it with React 17 nad it works.
Current peerDependency means that lib works with at least React 16.14 and should be updated to 16.14 - 17.x
So you can use it with React17 and I will update peerDependency.

**Comment by geiszla** [comment]
Any updates on this? It would be good to know that this package officially supports React 17.
