### ISSUE TITLE
Anyway to prevent send message after pressing "Enter" key?

### ISSUE THREAD

**Issue by beevekmgr** [chatscope/chat-ui-kit-react#28]
I want my message line break on enter press rather than shift + enter.. 
How do I prevent default behaviour of sending messages on enter pressed!!!

**Comment by supersnager** [comment]
@beevekmgr How do you want to send messages? Only using send button?

**Comment by beevekmgr** [comment]
Um... yes actually "enter" key is use to switch language in japanese . which is causing a problem.

**Comment by supersnager** [comment]
@beevekmgr Ok, I will add a property to disable send on enter

**Comment by supersnager** [comment]
@VincentRoest, thank you for your awesome work! 
I want to merge your PR, but the commit message needs to meet conventional commit requirements.
Please see my PR comment for the details.

**Comment by beevekmgr** [comment]
@supersnager  still waiting this to be merged...

**Comment by supersnager** [comment]
Sorry guys for having to wait. I forgot that that commit message can be changed before merge :)
