### ISSUE TITLE
The Message object in the MessageList stops displaying the sender and sentTime when using the direction property

### ISSUE THREAD

**Issue by SuppSoftAdminZ** [chatscope/chat-ui-kit-react#30]
Both the sender and sentTime display properly at first (when not using the direction property). However, once I applied the direction property (using either outgoing or incoming), the sender & sentTime no longer display. I tried using the sendor & sentTime in either the model object and the Message.Header object. But it will no longer display. Once I remove the direction property from the Message Model object, the sender & sentTime start displaying again.

Thanks

**Comment by supersnager** [comment]
Hi @SuppSoftAdminZ Thank you for your question.

I think the following issues can be helpful:
https://github.com/chatscope/chat-ui-kit-react/issues/11
https://github.com/chatscope/chat-ui-kit-styles/issues/2

If not, please come back and we will see what I can do about it.

**Comment by SuppSoftAdminZ** [comment]
Wow!  Thanks for the quick reply and all the options to resolve it. I will apply one of those options Thank you again!!On Sat, Apr 17, 2021 at 5:44 AM Super Snager ***@***.***> wrote:
Hi @SuppSoftAdminZ Thank you for your question.
I think the following issues can be helpful:
#11
chatscope/chat-ui-kit-styles#2
If not, please come back and we will see what I can do about it.

?You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
