### ISSUE TITLE
Is there a way to pass messages wrapped in component?

### ISSUE THREAD

**Issue by GyCtaB** [chatscope/chat-ui-kit-react#33]
Hi! Thanks for sharing cool chat kit!

Is there a way to pass wrapped in component chat messages without violating lib proptypes? 
```
function GroupOfFixedMessages() {
  return (
    <>
        <Message model={messageModel} />
        <Message model={messageModel} />
        <Message model={messageModel} />
    </>
  );
}

<MessageList>
  <Message model={messageModel} />
  
  <GroupOfFixedMessages />
 </MessageList> 
 ```
 
 The only way to fix proptypes violation that I found is explicitly set **as** prop to one of valid options but it feels kinda hacky.
 ```
 <GroupOfFixedMessages as="Message" />
 ```

**Comment by supersnager** [comment]
Hi @GyCtaB Using the **as** property with Message/MessageGroup value  is the recommended and the only way to achieve this :)

BTW, what exactly do you want to do? What for is the &lt;GroupOfFixedMessages /&gt;
Please describe your use case. Maybe I should add some new component?

**Comment by GyCtaB** [comment]
I'm using chat UI kit not as a "chat" but as a "interface that looks like chat". The main difference is that user doesnt have abilty to send messages, just browse "chat history". Due to specific of this use case I have messages that are logically grouped and conditionnaly displayed.

**Comment by supersnager** [comment]
@GyCtaB Thanks for your answer.
If messages are grouped, why not use **&lt;MessageGroup /&gt;** for this? What feature is missing that you need to use the custom component?
