### ISSUE TITLE
Feature Request: Jump to message

### ISSUE THREAD

**Issue by pateljoel** [chatscope/chat-ui-kit-react#38]
Especially for the search function, it would be nice if there is a way to jump to a specific message in the chat list and the chat window shows it directly.

Example: Discord
![discord](https://user-images.githubusercontent.com/64401775/116353734-38638280-a7ef-11eb-8416-fdea7b5a8ba0.png)

**Comment by supersnager** [comment]
Hi @pateljoel, thank you for your request.
This feature will be done as part of the #24.
