### ISSUE TITLE
Warnings shown when embedding wrapper child components

### ISSUE THREAD

**Issue by nzayatz14** [chatscope/chat-ui-kit-react#43]
Hi again,

This is not really an issue but more of an opinion. I've noticed some warnings are being shown when embedding "invalid" child elements into some components. Something like:

```
Warning: Failed prop type: "MyMessage" is not a valid child for MessageList. Allowed types: Message, MessageGroup, MessageSeparator, MessageListContent
```

My issue here is that this warning is shown if I try to wrap my components for custom logic or even just for cleaner code. For example, the following component would throw this warning.

```typescript
const MyMessage = (props: MessageProps) => {

    const {} = props;

    //some custom logic here

    return (
        <Message {...props} />
    );
};
```

Are these warnings shown on the production build as well? Or only the dev build?

Thanks!

**Comment by nzayatz14** [comment]
Another heads up that may be related to this @supersnager. I noticed that when I build for production, it looks like the custom components I have do not show up. I created separate components for my conversation header and input container of my chat.

The dev build looks like:

<img width="1240" alt="Screen Shot 2021-05-16 at 10 35 57 AM" src="https://user-images.githubusercontent.com/6536941/118401167-91764780-b632-11eb-9a29-86be41fc12a8.png">

Whereas the production build shows:

<img width="1242" alt="Screen Shot 2021-05-16 at 10 31 45 AM" src="https://user-images.githubusercontent.com/6536941/118401184-9fc46380-b632-11eb-8aa4-05b9638b6aab.png">

Any ideas? I feel like the components may be doing something wonky with the [getChildren](https://github.com/chatscope/chat-ui-kit-react/blob/master/src/components/utils.js) function and Typescript may be having some issues with it.

**Comment by supersnager** [comment]
Hey @nzayatz14,
it's difficult to say without the code, but I have some suspicions.

If you are using the **as** parameter with the type:
```javascrtipt
as={ConversationHeader}
```
try to use a string instead:

```
as="ConversationHeader"
```

**Comment by nzayatz14** [comment]
I actually passing the string currently. Heres a skeleton of my component

```jsx
<ChatContainer>
    <ChatHeader
        as='ConversationHeader'
       //other props
    />

    //MessageList and messages

    <ChatInputToolbox
        as='InputToolbox'
        //other props
    />
</ChatContainer>
```

**Comment by supersnager** [comment]
@nzayatz14 How you build your app for production? You are using CRA or something else?

**Comment by nzayatz14** [comment]
Yes, just using create-react-app so pretty standard I'd imagine. Also heres my tsconfig if this helps

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "."
  },
  "include": [
    "src"
  ]
}
```

**Comment by nzayatz14** [comment]
@supersnager so after digging into this a bit, it looks like your [getChildren](https://github.com/chatscope/chat-ui-kit-react/blob/master/src/components/utils.js) function is relying on the code to not be minified. However, the `ConversationHeader` and `InputToolbox` get minified on the production build, whereas the `MessageList` and `MessageInput` components do not. I believe this has something to do with `MessageList` and `MessageInput` being class based and `ConversationHeader` and `InputToolbox` being function based components.

Heres an example of the minified vs unminified classes:

Minified `ConversationHeader` component:
![Screen Shot 2021-05-18 at 7 21 38 AM](https://user-images.githubusercontent.com/6536941/118643433-8cd49f00-b7aa-11eb-91ad-8fc172faad5b.png)

Non-minified `MessageInput` component:
![Screen Shot 2021-05-18 at 7 22 05 AM](https://user-images.githubusercontent.com/6536941/118646397-26518000-b7ae-11eb-82a3-14f0d0ed2ab0.png)

So, in your [getChildren](https://github.com/chatscope/chat-ui-kit-react/blob/master/src/components/utils.js) function when you are looping through the `types` to get the `strTypes` here:

```javascript
var strTypes = types.map(function (t) {
    return t.name || t.displayName;
  });
```

Your result is not quite what you'd expect:

![Screen Shot 2021-05-18 at 7 50 02 AM](https://user-images.githubusercontent.com/6536941/118646628-70d2fc80-b7ae-11eb-9d76-a8eb38cdd66e.png)

Not sure how you want to move forward with this information, but what I've seen from most packages that have specified child props is they will throw a warning on the development build saying something like `This is not a valid child element of MyComponent, expecting MyChildComponent or MySecondChildComponent`. But on the production build, they will just ignore it and let it happen, not remove items that are not "supposed to be there."

Hope this helps

**Comment by supersnager** [comment]
@nzayatz14 Please check the 1.8.1 version, and let me know if it works for you.

**Comment by nzayatz14** [comment]
@supersnager this appears to fix the production build issue, thanks!
