### ISSUE TITLE
Can we show sender time in custom outgoing message?

### ISSUE THREAD

**Issue by GhazanfarKhan** [chatscope/chat-ui-kit-react#44]
Hi we need to show time in custom outgoing message as well like in incoming. Attached is the screenshot

![image](https://user-images.githubusercontent.com/16287368/119818672-ea828d00-bf08-11eb-9b5e-9602b18482dc.png)

please advice.

**Comment by supersnager** [comment]
@GhazanfarKhan You can use **&lt;Message.Footer /&gt;**

https://chatscope.io/storybook/react/?path=/docs/components-message--with-footer

However, if you have your own custom message it's up to you how you put the time in it.

**Comment by GhazanfarKhan** [comment]
Not showing in message footer also

**Comment by supersnager** [comment]
@GhazanfarKhan Please show your code

**Comment by GhazanfarKhan** [comment]
Here it is

`class ChatMessage extends React.PureComponent {
    render() {
        const { message: { sid, direction, date, body, username, deliveryReceipt } } = this.props;
        let component;
        if (direction == 'outgoing') {
            component = <Message key={sid} avatarPosition="tl" model={{
                direction: direction,
                type: 'custom',
                sentTime: date
            }}>
                <Message.CustomContent>
                    {body}
                    <DeliveryReceipt deliveryReceipt={deliveryReceipt} />
                </Message.CustomContent>
                <Message.Header />
                <Message.Footer sentTime={date} />
             
            </Message>
        }
        else {
            component =
                <Message key={sid} avatarPosition="tl" model={{
                    message: body,
                    sentTime: date,
                    direction: direction,
                    position: 'single'
                }}>
                    <Avatar src={CUSTOMER_ICON} name={username} />
                    <Message.Header sender={date} />
                </Message>
        }
        return component;
    }
}
`

**Comment by nzayatz14** [comment]
Hey @supersnager,

I came across this issue as well, it looks like it has to do with some of your SCSS styling in the styles library [here](https://github.com/chatscope/chat-ui-kit-styles/blob/master/themes/default/_variables.scss).

```scss
$show-message-outgoing-sender-name: false !default;
$show-message-outgoing-single-sender-name: false !default;
$show-message-outgoing-first-sender-name: false !default;
$show-message-outgoing-last-sender-name: false !default;

$show-message-incoming-sent-time: false !default;
$show-message-incoming-single-sent-time: true !default;
$show-message-incoming-first-sent-time: true !default;
$show-message-incoming-last-sent-time: false !default;

$show-message-outgoing-sent-time: false !default; //This one in particular
$show-message-outgoing-single-sent-time: true !default;
$show-message-outgoing-first-sent-time: true !default;
$show-message-outgoing-last-sent-time: false !default;
```

Not sure if you meant to disabled some of these displays by default, I feel like it would be very reasonable to allow for all messages to have header/footer types. I also need `$show-message-outgoing-sent-time` to be `true` for instance. 

@GhazanfarKhan I figured out a workaround of this for now. If you have custom styles you should just be able to override the `cs-message__sent-time` class (or whichever one you actually need) to always be `display: block;`

Heres my example in SCSS:
```SCSS
.cs-message--outgoing {
    .cs-message__sent-time {
      display: block;
    }
  }
```

Hope this helps!

**Comment by GhazanfarKhan** [comment]
Hi @nzayatz14 thanks for this. I changed css according to my requirements.

**Comment by nzayatz14** [comment]
@GhazanfarKhan I wouldn't close this issue just yet, at it hasn't actually been fixed, I've just provided a work around.

**Comment by supersnager** [comment]
@nzayatz14 @GhazanfarKhan This behavior is detailed here: https://github.com/chatscope/chat-ui-kit-styles/issues/2
