### ISSUE TITLE
Maintain scroll positions both Y and X position.

### ISSUE THREAD

**Issue by GhazanfarKhan** [chatscope/chat-ui-kit-react#45]
Hi, can we make scroll position state so that during page navigation for large list we don't have to scroll from start position.

**Comment by supersnager** [comment]
@GhazanfarKhan Currently, this is not possible out of the box, but you can remember and set scroll position manually.

I will think about this feature.

Related to: #24

**Comment by GhazanfarKhan** [comment]
Well I used react-window library with your component, since my list are huge I dont want them to render all. react-window also provide scroll position and helper method to move to index or item.

Thanks.

**Comment by francesc79** [comment]
> Well I used react-window library with your component, since my list are huge I dont want them to render all. react-window also provide scroll position and helper method to move to index or item.
> 
> Thanks.

Could you share your code for show the integration with react-window?
