### ISSUE TITLE
<ConversationHeader.Back> example usage

### ISSUE THREAD

**Issue by myamann** [chatscope/chat-ui-kit-react#47]
Hello is there any example code for <ConversationHeader.Back> component?

**Comment by supersnager** [comment]
@myamann I don't have an example ready yet, but I will prepare something.
Please tell me what do you exactly need. Do you want to know how to hide the left column with conversation list?

**Comment by myamann** [comment]
Main container is working fine with responsive feature but when i resize the client for smaller screen conversation section is hide. I want to know how to write "show" "hide" function for conversation back button. Like yours example demo on the website. could you explain this please?

**Comment by supersnager** [comment]
@myamann I have prepared an example here: [Toggle conversation list using the back button
](https://chatscope.io/storybook/react/?path=/story/components-maincontainer--toggle-conversation-list-using-the-back-button)

This is a very simple example, and it can be done in many different ways, but you got the idea.

I hope it will help, but in an advanced application, I would rather do this based on routing, where the conversation list is on a dedicated route.
