### ISSUE TITLE
Typing Indicator onFocus

### ISSUE THREAD

**Issue by ash-buzz** [chatscope/chat-ui-kit-react#48]
Please have an option to make the typing indicator visible when the message input is active or focussed.

**Comment by supersnager** [comment]
@ash-buzz You can show a typing indicator whenever you want, depending on your state.

If you want to show it on **&lt;MessageInput /&gt;** focus just set a visibility flag to true in an onFocus event and use the flag to show the indicator.

```jsx
import {useState} from "react";
import {ChatContainer, MessageList, MessageInput} from "@chatscope/chat-ui-kit-react"

const [typingIndicator, setTypingIndicator] = useState(false);

<ChatContainer>

  <MessageList typingIndicator={typingIndicator && <TypingIndicator content="Emily is typing" />}>
  </MessageList>

  <MessageInput onFocus={() => setTypingIndicator(true)} />

</ChatContainer>
```
