### ISSUE TITLE
fancyScroll customization to show without hover

### ISSUE THREAD

**Issue by ash-buzz** [chatscope/chat-ui-kit-react#49]
Is it possible to customize  fancyscroll such that it is visible all the time and not only on hovering?

**Comment by supersnager** [comment]
@ash-buzz Thank you for your question.
The fancy scroll is based on [perfect-scrollbar](https://github.com/mdbootstrap/perfect-scrollbar#options) which doesn't have such an option. So unfortunately it's currently not possible.

Additionaly, there are many problems with perfect-scrollbar which is also not actively maintained (I waited almost a year for a version with my fix to be released ).

So, I'm working on a new fancy scroll implementation. I will add this feature to the new version.
