### ISSUE TITLE
Delivered devices count in delivery receipt

### ISSUE THREAD

**Issue by armor009** [chatscope/chat-ui-kit-react#50]
In the case of multi device mobile or web, the user is logged in with multiple devices on multiple platforms. Can there be a delivered devices count for delivery receipts.

It ensures that delivered indicator is sent with more precise information if only one device, say receives the message. This is particularly relevant if the message is received at a device that the user does not use frequently or is not using for certain time period. It sets user expectation of message delivery and recipient's response.

**Comment by supersnager** [comment]
@mayank-mundhra-2012 Thanks for your question. I can add this feature. Please provide some example image of how you would you like it to look.
