### ISSUE TITLE
How to add checkbox element before avatar - Conversation List

### ISSUE THREAD

**Issue by waqasali26041995** [chatscope/chat-ui-kit-react#51]
Hey I want to use checkbox before avatar in conversation list page for delete multiple conversation but <conversation> tag not accept checkbox element. I'm stuck in this issue last 2 days but can't find solution so please give me better solution.

Code:
`<Conversation
                        className="multi-select-conversation"
                        active={sid === selected}
                        style={style}
                        key={index}
                        onClick={selectChannel}
                        name={friendlyName}
                        info={lastMessage?.body?.length > 35 ? lastMessage?.body?.substring(0, 35) + '.' : lastMessage.body}
                        unreadCnt={unread_messages_count}
                        lastActivityTime={lastMessage.dateCreated ? moment(lastMessage.dateCreated).fromNow() : ''}
                    >
 <Avatar src={CUSTOMER_ICON} status="available" />
                        <Conversation.Operations>
                            <EllipsisButton orientation="vertical" onClick={handleMenuClick} />
                        </Conversation.Operations>
</Conversation>`

**Comment by supersnager** [comment]
@waqasali26041995 Thank you for your question, I think this recipe should help: [Changing component type to allow place it in container slot
](https://chatscope.io/storybook/react/?path=/story/documentation-recipes--page)

If you will have any questions about how to use it in your case don't hesitate to ask here.
