### ISSUE TITLE
Refocus MessageInput after it was disabled

### ISSUE THREAD

**Issue by chloe-schoreisz** [chatscope/chat-ui-kit-react#54]
I set the `disabled` prop of messages to `true` while sending. This caused the input box to not be refocused once reenabled. Would it be possible to refocus the message once the prop `disabled` is `false` ?
<img width="559" alt="Screen Shot 2021-08-18 at 5 42 50 PM" src="https://user-images.githubusercontent.com/81575628/129929070-f8135939-0320-4ba9-94fb-ada67be137fd.png">
<img width="576" alt="Screen Shot 2021-08-18 at 5 42 56 PM" src="https://user-images.githubusercontent.com/81575628/129929077-0622b56f-a3b5-409f-84e2-dc4461f54021.png">
<img width="470" alt="Screen Shot 2021-08-18 at 5 41 36 PM" src="https://user-images.githubusercontent.com/81575628/129928788-041e17cd-d06e-400f-9ea5-c7bd4716e8dc.png">

**Comment by supersnager** [comment]
Hi @chloe-schoreisz,  thank you for your question.

The focus can be set using the **focus()** method provided by the **&lt;MessageInput /&gt;** component.

e.g.

```jsx
const inputRef = useRef();
const [disabled, setDisabled] = useState(false);

const sendMessage = () => {
 setDisabled(true);
 senToWire().then( () => {
  inputRef.current.focus();
  setDisabled(false);
});

<MessageInput ref={inputRef} onSend={sendMessage} disabled={disabled} />
```

**Comment by chloe-schoreisz** [comment]
Would this be considered a common use case ? I wonder if it this behaviour should be native to the component.
What other common use cases for the `disable` props do you have ?

**Comment by supersnager** [comment]
@chloe-schoreisz I'm not sure if it is a common use case.
Why do you want disable the input, when a message is sending? If you do it, the user will not be able to write the next message untill the previous one is sent.

What exactly behavior do you consider native, disabling while sending or refocus after sent?

BTW, sorry I forgot about one property **activateAfterChange** it's meant for a different use case, but you can try setting it to true to automagically set the focus after sending.

Other common use cases for the **disabled** prop are for example when you have no active user selected, or when connection to server has not been established. Depending on the application, you may also want to block messages from being sent to the user when they are not connected.
