### ISSUE TITLE
Conversation lastActivityTime prop doen't support node

### ISSUE THREAD

**Issue by jonasboardwalker** [chatscope/chat-ui-kit-react#55]
## Description 

Almost all the props in the Conversation component support node as a child (e.g. info, name) except for the lastActivityTime. I need to use a suspense for the Last Activity Time so it will show skeleton when value is still loading. And it works, but still throws and error to the console. I would be handy to allow node for this field.

<img width="1015" alt="Screenshot 2021-10-05 at 11 00 25" src="https://user-images.githubusercontent.com/20488748/135993194-41f0c76b-cffc-4d13-b782-e5d3583979b0.png">

**Comment by supersnager** [comment]
@jonasboardwalker Thank you for your commitment.  I have fixed this. Enjoy!

**Comment by supersnager** [comment]
Storybook example: [lastActivityTime property as a React node](https://chatscope.io/storybook/react/?path=/story/components-conversation--last-activity-time-as-react-node)
