### ISSUE TITLE
Scroll to bottom when new message arrives

### ISSUE THREAD

**Issue by GhazanfarKhan** [chatscope/chat-ui-kit-react#6]
Hi, Thanks for your awesome work. I have a scenario where I have to scroll to bottom when new message arrives. Did their any apis for this.

Thanks

**Comment by supersnager** [comment]
Hi @GhazanfarKhan thanks for your feedback.
Scroll to bottom should work out of the box. Please share sample of not working code.

**Comment by GhazanfarKhan** [comment]
Hi @supersnager if there is a scroll in messages like more than 50 messages and my scroll is on top so when new message arrives scroll doesn't move to the last message. Is there any way to do that?

**Comment by supersnager** [comment]
@GhazanfarKhan Currently there is no api method to scroll to bottom programatically.
Of course you can set scroll position "manually" by searching for scroll container in dom tree, but it does not make sense :)
I will add scrollToBottom method do MessageList component.
If all goes well, this feature will be available today.

**Comment by supersnager** [comment]
Done in release [v1.2.0](https://github.com/chatscope/chat-ui-kit-react/releases/tag/v1.2.0).
I have also added new prop to MessageList - scrollBehavior. It allows to set default scroll behavior for this component.
For documentation please visit: [chat-ui-kit-react MessageList.scrollToBottom method example](https://chatscope.io/storybook/react/?path=/docs/components-messagelist--scroll-to-bottom).

@GhazanfarKhan Please check it and let me know is it ok for you.

I'm also considering to add a property to scroll automatically always when new message will be added.

**Comment by GhazanfarKhan** [comment]
Hi,

const scrollBehavior = select(label, options, undefined);

what is select in this?

**Comment by supersnager** [comment]
@GhazanfarKhan This is only for Storybook knobs.
Value from this select is passed as prop to MessageList.
**scrollBehavior** property has two posisible values: "auto" or "smooth". It is documented here: https://chatscope.io/storybook/react/?path=/docs/components-messagelist--long-list-with-scrollbar#props

For knobs please see attached screenshot.
You can switch on addon tabs with knobs by pressing "a" on the keyboard in Storybook, or by choosing "Show addons" from Storybook menu in top left corner. 
![image](https://user-images.githubusercontent.com/6375504/103542045-a381f580-4e9c-11eb-9008-9ce3e1648d2e.png)

**Comment by GhazanfarKhan** [comment]
Thank You!. Working fine.
