### ISSUE TITLE
Example with simple integration receiving JSON via REST or Websocket.

### ISSUE THREAD

**Issue by drksbr** [chatscope/chat-ui-kit-react#62]
Forgive me if I missed something, but I've seen all the examples available, but I still couldn't make something workable.
It would be possible to provide an example in which Chats and Messages are loaded via JSON, either receiving via REST or Websocket.
Thank you in advance for your patience and understanding.

**Comment by supersnager** [comment]
@drksbr Thank you for your question.
I've been working on a simple chat server and examples you need for some time. However, it will still be a while before this is ready.

In the meantime, please describe your specific problem, preferably share your code. I'll try to help.

**Comment by ricco-douro** [comment]
Hey @supersnager, great job you are doing. Can I help you speed it up? I am willing to contract you to deliver a functional system with a simple text only based server. Are you available and willing?

**Comment by supersnager** [comment]
@ricco-douro Sure, why not. please DM me on [Discord](https://discord.gg/TkUYWQRf2M) or [Twitter](https://twitter.com/chatscope).
