### ISSUE TITLE
Message typescript

### ISSUE THREAD

**Issue by alexbakers** [chatscope/chat-ui-kit-react#74]
Hello.

Can you tell me what's the matter?

<img width="973" alt="image" src="https://user-images.githubusercontent.com/98721968/184178273-0700e628-dcc8-4e6f-a405-4d69e1a1eaf0.png">

Thank you.

**Comment by supersnager** [comment]
@alexbakers You need to add **direction** and **position** properties to the model object:

e.g.:

```typescript
{
  message: "Hello my friend",
  sentTime: "just now",
  sender: "Joe",
  position: "normal",
  direction: "incoming"
}
```

**Comment by alexbakers** [comment]
Thx.
