### ISSUE TITLE
How can I add button inside MessageInput Like emoji button to open emoji picker.

### ISSUE THREAD

**Issue by jaipatel248** [chatscope/chat-ui-kit-react#75]
Coming to the issue/feature request, 
currently MessageInput I want to add a button for emoji to open emoji picked. 
If I can add a button near to attachment it will still work.

**Comment by supersnager** [comment]
@jaipatel248 The following sources should help:

#7 

https://chatscope.io/storybook/react/?path=/docs/components-chatcontainer--wrapped-message-input#wrapped-messageinput

https://chatscope.io/storybook/react/?path=/docs/documentation-recipes--page#changing-component-type-to-allow-place-it-in-container-slot

**Comment by jaipatel248** [comment]
Thanks for the help.
I think you should add that details in MessageInput's documentation as well or put a link.

**Comment by supersnager** [comment]
@jaipatel248 You are right, I was just looking for it myself there :rofl:
