### ISSUE TITLE
ConversationContent type inconsistency

### ISSUE THREAD

**Issue by victorchapado** [chatscope/chat-ui-kit-react#76]
I found an inconsistency between the definition of the [`ConversationContent` type definition](https://github.com/chatscope/chat-ui-kit-react/blob/9d412857849bebee1a736253607bbce4dc2edf19/src/components/Conversation/Conversation.d.ts#L10) and the component implementation. The definition declares the property as a React.Node but the implementation only accepts `string`:

[source](https://github.com/chatscope/chat-ui-kit-react/blob/9d412857849bebee1a736253607bbce4dc2edf19/src/components/Conversation/ConversationContent.jsx#L40)
```js
{typeof lastSenderName === "string" && (
  <LastSenderName name={lastSenderName} />
)}{" "}
```

IMHO, I suggest continuing to accept a React node to be more flexible, something like this:
```js
{typeof lastSenderName === "string" ? (
  <LastSenderName name={lastSenderName} />
) : lastSenderName}{" "}
```

Thanks!

**Comment by supersnager** [comment]
@victorchapado thanks for your vigilance!
