### ISSUE TITLE
Disable rendering of html in messages?

### ISSUE THREAD

**Issue by iocuydi** [chatscope/chat-ui-kit-react#82]
Is there any way to make the text element of messages be actual text? Rather than interpreting it as html. For example if I send `<button/>`
`<button/>` as a message, it shows a message with an html button inside it, rather than the text `<button/>`.

**Comment by j-krl** [comment]
You're saying if you send a message with the text "<button/>", your message renders button inside of it? That certainly doesn't happen for me

**Comment by j-krl** [comment]
Actually I see what you mean now. I was able to copy-paste html directly into the MessageInput, and the HTML even rendered inside the input. What you can do is use the second argument of the provided onSend function, as this is just the text content of the message. I haven't figured out how to disable html rendering in the input yet though.

**Comment by supersnager** [comment]
@iocuydi Message content is rendered depending on the provided **type** property. The default type is "html".
With this type the content is inserted using dangerouslySetInnerHTML: https://github.com/chatscope/chat-ui-kit-react/blob/170191a5f6d0d3190493b08c309cb0fca237f5ca/src/components/Message/MessageHtmlContent.jsx#L14

That is why your content is rendered as is. Depending on what you exactly want to do you can sanitize the content, change the type of the message (like @j-krl said) or do both.

@j-krl The MesageInput is a contenteditable div, so If you want to prevent displaying html you can sanitize the pasted content.
We need to do some magic here.
Something like this:
```typescript
    const onPaste = useCallback((e: React.ClipboardEvent<HTMLDivElement>) => {

      // Block default browser action
      e.preventDefault();
      
      const selection = window.getSelection();
      
      if ( selection ) {
        
        const range = selection.getRangeAt(0);
        
        // Clean the html by getting only the text content from the pasted data
        const text = e.clipboardData.getData("text/plain");
        
        // Something can be actually selected, so we need to delete it
        range.deleteContents();

        // Paste clean text at the cursor position
        range.insertNode(document.createTextNode(text));
        
        // Move cursor to the end ef the pasted text
        selection.collapseToEnd();
        
        // Get the editor reference
        const editor = document.querySelector(".cs-message-input__content-editor") as HTMLDivElement;
        
        if ( editor ) {
         // The value was inserted into the editor without changing the state.
         // We don't want to change the state, because it causes problems with placing the cursor in the right place,
         // and if the input was empty the send button will remain disabled.
         // So we need to dispatch the "input" event manually.
         // This will trigger the onChange event, and the state will be updated
          editor.dispatchEvent(new Event("input", {bubbles: true}));
        }
        
      }
    },[]);
    
```
