### ISSUE TITLE
Great project usable to create intercom style widget?

### ISSUE THREAD

**Issue by Jarrodsz** [chatscope/chat-ui-kit-react#88]
For an opensource project i require an intercom style chatwidget as minimal imemrntatikn. Could i use thus project for that?

basically i want a minimal imementation build upon my own orm. I assume there is an api to get data from and into the widget.

any advice regarding rhat?🙏
If not this project what other prijects could i look at.

**Comment by supersnager** [comment]
@Jarrodsz Yes, you can use this library to build a chat widget.
Here you have some resources about this:

https://chatscope.io/blog/web-widgets-part-1-what-is-it/
https://chatscope.io/blog/web-widgets-part-2-widget-him/
https://chatscope.io/blog/web-widgets-part-3-api-cookbook/
https://chatscope.io/blog/web-widgets-bonus-why-iframe/

Simple widget: https://mars.chatscope.io/
On the [Widgeton](https://chatscope.io/widgeton-beta/) website, click the **Compile** button, and go to the "Test" tab, to see a loaded chat widget.

The [use-chat library](https://github.com/chatscope/use-chat) should also be helpful.
