### ISSUE TITLE
OnKeyDown event occurs twice when typing in Korean and then hitting enter

### ISSUE THREAD

**Issue by HwangTaehyun** [chatscope/chat-ui-kit-react#9]
Hi, thank you for intuitive and awesome chat-ui library.

I'm using it well, but there are some bugs like following situations.

OnKeyDown event occurs twice when typing in Korean and then hitting enter. So Last Korean Character printed one more time.
![Korean Input Bug](https://user-images.githubusercontent.com/42465090/107186368-7b4f5e80-6a27-11eb-9a12-bde0378ca20b.gif)

**Comment by supersnager** [comment]
@HwangTaehyun Thanks for PR. I will reproduce this bug before merging, and check if everything works for other edge cases as well.

**Comment by HwangTaehyun** [comment]
I checked again, and it works fine in Chrome on Windows, and it seems that this problem occurs in Chrome on Mac. Please note. Thank you!

**Comment by supersnager** [comment]
@HwangTaehyun Thanks!

**Comment by kolt-suzuki** [comment]
This issue is critical for Japanese users too.
I hope it would be merged quickly.

**Comment by supersnager** [comment]
@kolt-suzuki I will take care of it this week.

**Comment by supersnager** [comment]
@HwangTaehyun @kolt-suzuki 
The PR from @HwangTaehyun uses onkeypress event which is unfortunately deprecated.
I don't want to keep deprecated features in the code.
However, I have done some research and it looks like there is no other workaround for this chrome bug.
So I have tested the PR and it's ok. I will merge it, but @HwangTaehyun please change the commit message as I mentioned in the PR comment.

**Comment by beevekmgr** [comment]
Waiting for ticket to merged....

**Comment by supersnager** [comment]
@HwangTaehyun  Thank you for your contribution!

**Comment by HwangTaehyun** [comment]
@supersnager Thank you for your effort!
