### ISSUE TITLE
MessageInput on Firefox appends `<br>`

### ISSUE THREAD

**Issue by philipmw** [chatscope/chat-ui-kit-react#91]
When I use chat-ui-kit-react version 1.10.1 in a basic app, the input works fine on Chrome, but on Firefox, it reliably adds `<br>` to my every input message. This happens both when I press Enter into the input box and when I click the Send button with the mouse.

For example, if I submit "hello world", on Firefox the send-message callback receives `hello world<br>` string. On Chrome, it is `hello world` as expected.

**Comment by iocuydi** [comment]
I was running into something similar, I was taking the first arg passed back by the MessageInput onChange component, and using that as the message. I found that actually, the MessageInput passes back multiple arguments and the first one is HTML, which will often have tags and such.

https://github.com/chatscope/chat-ui-kit-react/blob/170191a5f6d0d3190493b08c309cb0fca237f5ca/src/components/MessageInput/MessageInput.jsx#L174

My solution was to maintain two state variables, one to hold the HTML to render the content of the message input (innerHTML, from above link), the other to actually send for the message with onSend (innerText, from above link).

Not 100% sure about the difference between these 3, but it seems that only innerText will maintain the correct formatting for the sent message, and only innerHTML will maintain the correct formatting for what should render in the MessageInput.
