### ISSUE TITLE
Access to MessageInput value via ref?

### ISSUE THREAD

**Issue by titocosta** [chatscope/chat-ui-kit-react#93]
I would like to access the value in MessageInput using `useRef` rather than the `value` / `onChange` controlled behavior to avoid unnecessary re-renderings for every key stroke.

Using the usual pattern:
```
const inputRef = React.useRef();
...
<MessageInput ref={inputRef} />
```

The `inputRef.current` object doesn't get the `value` field, probably because the reference is passed to a parent 1-2 levels above the actual textfield.

Any suggestions?

**Comment by supersnager** [comment]
@titocosta Thank you for the question.

MessageInput editor is a contenteditable div.
A direct reference to this div is not exposed. However, you can access it using the querySelector.

```typescript
useEffect(() => {
  const editorRef = useRef<HTMLDivElement | null>(null);
  const msgInput = document.querySelector(".cs-message-input__content-editor") as HTMLDivElement;
  editorRef.current = msgInput;
},[]);
```
I know it should be done in a better way, so I have created a dedicated issue for this #95.

**Comment by titocosta** [comment]
Thanks. It works if I use `document.querySelector("div.cs-message-input__content-editor")`, surprisingly without `div` it always returns null.

**Comment by titocosta** [comment]
I think this approach creates race conditions, editorRef is often null and unreliable even adding to useEffect on every render.

**Comment by supersnager** [comment]
@titocosta What do you mean by "race conditions"?

**Comment by titocosta** [comment]
Meaning the behavior is not deterministic, depending on how the page is
loaded up, etc.
