### ISSUE TITLE
`Property 'as' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'`

### ISSUE THREAD

**Issue by jimmykane** [chatscope/chat-ui-kit-react#99]
Example from recipeis 

```
<div as={MessageInput}>
          <MessageInput />
          <button>Custom button</button>
        </div>
```

Typescript 

`Property 'as' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'`

**Comment by aledeloss** [comment]
Hi! I am having the same issue here, any comments of fixes on this? Thank you!

**Comment by supersnager** [comment]
@jimmykane @aledeloss There are two ways to fix it.

1. You can augment the 'react' module and add the `as` attribute:
```typescript
declare module 'react' {
    interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
        as?: string | typeof MessageInput;
    }
}
```

or 

2. Wrap the div with an additional component that has the `as` property:

```typescript
interface ExtentedInputProps extends MessageInputProps {
    as?: string | typeof MessageInput;
}

const ExtendedInput = (props:ExtentedInputProps) => {
    return (
        <div>
            <span>Custom content</span>
            <MessageInput />
        </div>
    );
}

<ChatContainer>
  <MessageList></MessageList>
  <ExtendedInput as={MessageInput} />
</ChatContainer>
```

**Comment by supersnager** [comment]
I have added this explanation to the documentation: 
https://chatscope.io/storybook/react/?path=/docs/documentation-recipes--page#what-about-typescript

**Comment by jimmykane** [comment]
Thank you !
